export const storeProducts = [
  {
    id: 1,
    title: "Google Pixel - Black",
    img: "img/product-1.png",
    price: 189,
    company: "GOOGLE",
    info: "The Google Pixel 6 in stormy black color is a Dual SIM smartphone (nano SIM+eSIM) with 5G technology, 128GB of storage and 8GB of RAM, 6.4-inch AMOLED FHD+, HDR10+ screen, 50+12MP rear cameras and 8MP front camera, Google Tensor processor and 4614mAh battery with 30W fast charge.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Samsung S7",
    img: "img/product-2.png",
    price: 160,
    company: "SAMSUNG",
    info: "The Samsung Galaxy S7 features a 5.1-inch Quad HD Super AMOLED screen, Qualcomm's most powerful Snapdragon 820 system chip under the hood and a brand new 12-megapixel camera with low light superpowers. All of that runs on a new edition of TouchWiz on top of Android 6 Marshmallow. And yes, the microSD card slot is back: you can use a card of up to 200GB onf the S7. The Galaxy S7 also has a very large, 3000mAh battery and it adds IP68 water resistance",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "HTC 10 - Black",
    img: "img/product-3.png",
    price: 136,
    company: "htc",
    info: "The HTC 10 is a beautifully crafted smartphone with a gorgeous display and an ergonomic design. This phone is the first to have optical image stabilisation for the front facing camera, which does help when shooting in low light. The phone has very snappy performance thanks to the Snapdragon 820 SoC, 4GB of RAM and 32GB of onboard storage. The USB Type-C port gets USB 3.1 Gen 1 speeds for faster data transfers. Sense UI is now leaner than ever, with many of the custom apps traded in favour of Google's native apps. Camera performance is good thanks to the 12 Ultrapixel 2 sensor, OIS and laser autofocus. The built-in battery lasts an entire day but doesn't do too well if you watch a lot of videos. Overall, the HTC 10 is a solid flagship that can go toe-to-toe with the best in the business.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "HTC 10 - White",
    img: "img/product-4.png",
    price: 140,
    company: "htc",
    info: "The HTC 10 is a beautifully crafted smartphone with a gorgeous display and an ergonomic design. This phone is the first to have optical image stabilisation for the front facing camera, which does help when shooting in low light. The phone has very snappy performance thanks to the Snapdragon 820 SoC, 4GB of RAM and 32GB of onboard storage. The USB Type-C port gets USB 3.1 Gen 1 speeds for faster data transfers. Sense UI is now leaner than ever, with many of the custom apps traded in favour of Google's native apps. Camera performance is good thanks to the 12 Ultrapixel 2 sensor, OIS and laser autofocus. The built-in battery lasts an entire day but doesn't do too well if you watch a lot of videos. Overall, the HTC 10 is a solid flagship that can go toe-to-toe with the best in the business.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "HTC Desire 626s",
    img: "img/product-5.png",
    price: 150,
    company: "htc",
    info: "HTC Desire 626s mobile was launched in July 2015. The phone comes with a 5.00-inch touchscreen display offering a resolution of 720x1280 pixels. HTC Desire 626s is powered by a 1.1GHz quad-core Qualcomm Snapdragon 210 processor. It comes with 1GB of RAM. The HTC Desire 626s runs Android 5.1 and is powered by a 2000mAh removable battery.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Vintage Iphone",
    img: "img/product-6.png",
    price: 100,
    company: "apple",
    info: "The iPhone 4 is now boxier, with the rear side now flat, instead of rounded. It will keep the 3.5-inch display diagonal, but will quadruple the pixels to 640x960, making it the highest-resolution screen on a smartphone to date. Apple actually calls the new screen Retina Display, because it shows 326 pixels per inch, while the human eye can only distinguish around 300 ppi. In addition, the screen will utilize the LCD IPS technology (same as in the iPad). The other new stuff includes a front-facing video call camera, 5MP main camera lens with LED flash and 720p HD video recording, Micro-SIM slot, instead of ordinary SIM, a secondary mic for noise-cancellation and a lot of other new features.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Iphone 7",
    img: "img/product-7.png",
    price: 649,
    company: "apple",
    info: "The Apple iPhone 7 is the successor to the highly acclaimed iPhone 6s. As such, it brings a multitude of enhancements in key areas, including design, performance, and user experience. While the overall shape and size of the phone have been left intact, there are now glossy and matte black options available. Also, the handset is now IP67-certified, making it water-resistant. On its back, the refined 12MP camera features optical image stabilization, wider aperture of F1.8, and a quad LED TrueTone flash for better low-light performance. Battery life has been given a welcome boost that could provide users around 2 hours of additional use time. The new A10 Fusion chip is up to 40% more powerful than last-year's A9, yet promises great power efficiency. And while the iPhone 7 lacks an audio jack, the box includes Lightning connector EarPods, as well as a Lightning to 3.5mm adapter.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Smashed Iphone",
    img: "img/product-8.png",
    price: 20,
    company: "apple",
    info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const detailProduct = {
  id: 1,
  title: "Google Pixel - Black",
  img: "img/product-1.png",
  price: 10,
  company: "google",
  info: "Lorem ipsum dolor amet offal butcher quinoa sustainable gastropub, echo park actually green juice sriracha paleo. Brooklyn sriracha semiotics, DIY coloring book mixtape craft beer sartorial hella blue bottle. Tote bag wolf authentic try-hard put a bird on it mumblecore. Unicorn lumbersexual master cleanse blog hella VHS, vaporware sartorial church-key cardigan single-origin coffee lo-fi organic asymmetrical. Taxidermy semiotics celiac stumptown scenester normcore, ethical helvetica photo booth gentrify.",
  inCart: false,
  count: 0,
  total: 0,
};
